### ISSUE TITLE
[BUG] Documentation not clear for me

### ISSUE THREAD

**Issue by ogezue** [hashicorp/vault-action#128]
**Describe the bug**
I'm trying to understand the syntax but run into syntax errors. It would be good to have a full example how to fetch and echo them 

**To Reproduce**
```
jobs:
Testing:
    runs-on: macOS-latest
    steps:
 - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action
	  
-----
Invalid workflow file
The workflow is not valid. .github/workflows/ci.yaml (Line: 40, Col: 13): Expected format {org}/{repo}[/path]@ref. Actual 'hashicorp/vault-action',Input string was not in a correct format.
-----
       with:
         url: https://vault.prod.myCompany.com
         githubToken: ${{ secrets.GIT_ACCESS_TOKEN }}
         secrets: secrets/app/show/iOS p12Key 
    - name: Fetching Signing Certificate from Vault
      run: echo "P12-key-value ${{steps.secrets.outputs.p12Key}}"
```

**Expected behavior**
Publish an example how to fetch and echo secrets

If you think the documentation is ok then it would be great to know how I can reach my goal :)
