### ISSUE TITLE
[BUG] Vault-action does not support authentication only usage

### ISSUE THREAD

**Issue by Ameausoone** [hashicorp/vault-action#152]
**Describe the bug**
I want to use vault-action only to authenticate to vault instance with an approle, and generate a `VAULT_TOKEN` to use with Terraform and vault-provider, and without retrieve secrets. But vault-action require to specify secrets. 

**To Reproduce**
Use vault-action without secrets : 

```yaml
      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: https://my-vault-instance
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportToken: true
```

**Expected behavior**

`vault-action` should authenticate and produces a masked environment variable `VAULT_TOKEN`. 

**Log Output**

```
Error: Input required and not supplied: secrets
```

**Additional context**
N/A
