### ISSUE TITLE
[FEAT] Please document that selector are using JSONata

### ISSUE THREAD

**Issue by mook-as** [hashicorp/vault-action#153]
**Is your feature request related to a problem? Please describe.**
I'm using a kv2 store, with a key that had a dash: `foo-bar`.
This produced errors that we difficult to resolve: `Unable to retrieve result for data.data.foo-bar. No match data was found. Double check your Key or Selector.`

Upon reading the source code, I found [references](https://github.com/hashicorp/vault-action/blob/2ca76a4465bca4f71fc88320e67551a287f7eaec/src/action.js#L136) to [JSONata](http://docs.jsonata.org); reading their docs, I found that I could escape things with backquotes, and this resolved the issue.

**Describe the solution you'd like**
Please add in the [relevant section in the README](https://github.com/hashicorp/vault-action#key-syntax) that the selector syntax is using JSONata.

**Describe alternatives you've considered**
I guess ripping the library out and doing something home-grown is fine too? But that seems like a lot of work, and the actual problem is just documenting it (which would have to be done either way).

**Additional context**
```yaml
uses: hashicorp/vault-action@v2.0.1
```

**Comment by doowb** [comment]
In case this is helpful to anyone else that needs to retrieve the entire JSON object from the secret, you can use `$.$` as the selector:

```yaml
secrets: secret/path/to/my-secret $.$ | MY_SECRET;
```

Just using `$` or `*` might have worked with `jsonata`, but the selector is [quoted here](https://github.com/hashicorp/vault-action/blob/937d792a86ee3746b4ad9ab3252d3b08d6a035a6/src/secrets.js#L41-L43) when it doesn't contain a `.`. It would be nice to be able to just do `.` or `*` to get the entire object, but I think that would be a separate feature request and I'm not sure where it would fit.

**Comment by anthonydahanne** [comment]
@doowb thanks so much for sharing $.$ - I could not find another way to grab the entire JSON under data.data !!!

**Comment by dcmoore-gd** [comment]
Same thank you @doowb!

**Comment by RichiCoder1** [comment]
This has bit enough people that I'll see if I can document this as well as add an easier wildcard shortcut.

**Comment by benkeil** [comment]
after one year, any progress here? how could such a basic feature not be included from the first day?

**Comment by maxcoulombe** [comment]
Hi, I was going to look at this issue but could no reproduce the problem with a quick test. Can anybody confirm if I am doing something wrong or perhaps the issue has been fixed since this was opened?

Create a Vault KV secret with dashes:
```
curl -X POST -H "X-Vault-Token: $VAULT_TOKEN" -d "{"data": {"secret-with-dashes": "my-secret"}}" $VAULT_ADDR/v1/secret/data/test-with-dash
```

Read the secret with dashes in a vault-action:
```
jobs:
  build:
    name: local-test
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/secret-with-dashes my-secret | DASH
```

Vault version:
`Vault v1.12.3`
