### ISSUE TITLE
[BUG] Response code 400 (Bad Request) when using approle auth

### ISSUE THREAD

**Issue by adamtharani** [hashicorp/vault-action#235]
**Describe the bug**
When trying to use the approle method to authenticate vault, the action breaks with a `Response code 400 (Bad Request)`

**To Reproduce**
```yaml
- name: Import Secrets from Vault
  uses: hashicorp/vault-action@0451f06f9f705768363122da079f46746e31bfe4
  with:
    url: https://vault.***********:8200
    method: approle
    roleId: ${{ secrets.VAULT_ROLE_ID }}
    secretId: ${{ secrets.VAULT_SECRET_ID }}
    caCertificate: ${{ secrets.CA }}
    secrets: |
```

**Expected behavior**
The action to return my secrets.

**Log Output**
`Error: Response code 400 (Bad Request)`

**Additional context**
