### ISSUE TITLE
Access vault using kubernetes method

### ISSUE THREAD

**Issue by shafiz1** [hashicorp/vault-action#237]
**Describe the bug**
I am trying to access vault secrets using kube auth on self hosted action runner
I could see the input it requires is the vault role and kubernetes token path

When I use them It fails with `Error: Response code 400 (Bad Request)`

**To Reproduce**

```yaml
- name: Get secrets from Vault
  uses: hashicorp/vault-action@v2.3.0
  with:
          url: https://vaultdev.rw.discoverfinancial.com
          method: kubernetes
          role: *************
          kubernetesTokenPath: **************
          secrets: |
                  ****************** USERNAME | TEST_USERNAME_;
                  ****************** PASSWORD | TEST_PASSWORD ;
```

**Expected behavior**
Fetch secrets from vault

**Log Output**
Get Vault Secrets
  ##[debug]Retrieving Vault Token from v1/auth/kubernetes/login endpoint
  ::endgroup::
Error: Response code 400 (Bad Request)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Get secrets from Vault

**Additional context**
Does this action supported kube auth on self hosted runner - as I see this in readme

kubernetes: you must provide the role paramaters. You can optionally override the kubernetesTokenPath paramater for custom mounted serviceAccounts. Consider kubernetes auth(https://www.vaultproject.io/docs/auth/kubernetes) when using self-hosted runners on Kubernetes:
