### ISSUE TITLE
403 (Forbidden) Issue when trying to pull secrets from my key value (kv) vault

### ISSUE THREAD

**Issue by rxa313** [hashicorp/vault-action#271]
Using `vault cli` I'm able to pull my secrets using:
```
vault kv get xxx/kv/some/secret/path
```

If I try to get the same secret and provide the same path using the action in my workflow:
```
     - name: import secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault.xxx.com:xxx
          token: ${{ secrets.VAULT_TOKEN }}
          #caCertificate: ${{ secrets.VAULTCA }} <- not required
          secrets:  xxx/kv/some/secret/path somesecret
```

I then get the `403 Forbidden` error in my output.

I thought that this action supported `kv get` or am I doing something wrong? In my local CLI I get the same `403 Permission Denied` error when trying to do `vault read xxx/kv/some/secret/path` , but if I execute `vault kv get ...` I can see the keys just fine.
