### ISSUE TITLE
[ISSUE] Error: Response code 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by plabate** [hashicorp/vault-action#278]
Hi,
I'm facing with an error while I try to communicate with my remote vault server from a github workflow.

The yaml of the `vault-action` is:

name: vault workflow
```
on:
 workflow_dispatch:
jobs:
  vault:
    runs-on: [ self-hosted, linux, x64, ec2 ]
    steps:
    - uses: actions/checkout@v2

    - name: Vault Secrets
      uses: hashicorp/vault-action@v2.0.1
      id: secrets
      with:
        url: http://my.eks.cluster.ip:<exposed_service_nodeport>/v1/kv/data/secret?version=1
        method: token
        tlsSkipVerify: true
        token: \${{ secrets.VAULT_TOKEN }}
        secrets: |
                 kv/secret foo | FOO`
```
The output of this action's step is:

```
Run hashicorp/vault-action@v2.0.1
with:
    url: http://my.eks.cluster.ip:<exposed_service_nodeport>/v1/kv/data/secret?version=1
    method: token
    tlsSkipVerify: true
    token: \***
    secrets: kv/secret foo | FOO
  
    exportEnv: true
Get Vault Secrets
Error: Response code 500 (Internal Server Error)
```

For the most verbose logs, I've added a secret called `ACTIONS_STEP_DEBUG` with the value true but it was useless.
I've tried to use
```
 - name: Vault Secrets
  uses: hashicorp/vault-action@v2.4.0
```
without success...
What can I do to retrieve my secrets?
Thank's to all.

**Comment by plabate** [comment]
UPDATE:

the error was because of my bad code. Here the correct workflow:

```
on:
 workflow_dispatch:
jobs:
  vault:
    runs-on: [ self-hosted, linux, x64, ec2 ]
    steps:
    - uses: actions/checkout@v2

    - name: Vault Secrets
      uses: hashicorp/vault-action@v2.0.1
      id: secrets
      with:
        url: http://my.eks.cluster.ip:<exposed_service_nodeport>/
        method: token
        #tlsSkipVerify: true
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
                 kv/data/secret foo | FOO
```

I can close the issue.
