### ISSUE TITLE
[BUG] The action doesn't override existing env variable when it is called second time through a separate action.

### ISSUE THREAD

**Issue by lurbanski-equinix** [hashicorp/vault-action#350]
**Describe the bug**
1. A job triggers an action X which call the vault-action.
2. New env variable  Y is set and has value VALUE1.
3. Job triggers the action X again where the vault-action is called in order to set the X var with different value e.g. VALUE2.
4. Bug - in the action X the Y var has still the value VALUE1.
5. In a next step of job there is correct value VALUE2

**To Reproduce**
The yaml of the `vault-action` step, with any sensitive information masked or removed.
```yaml
#job.yaml
name: Test workflow
on:
  workflow_dispatch:

jobs:
  Use_vault_throught_the_same_action_twice_using_hashicorp_vault:
    runs-on: [ REMOVED ]
    steps:
      - name: Log github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout source code
        uses: actions/checkout@v2

      - uses: ./.github/actions/lurbanski-hashicorp-action
        with:
          var: lurbanski1

      - uses: ./.github/actions/lurbanski-hashicorp-action
        with:
          var: lurbanski2

      - name: Show LURBANSKI_TEST
        run: |
          var=${{ env.LURBANSKI_TEST }}
          echo ${var:0:1}UUU${var:1}
```
```yaml
#lurbanski-hashicorp-action/action.yaml
name: lurbanski-hashicorp-action
description: lurbanski-hashicorp-action
inputs:
  var:
    description: lurbanski1, lurbanski2
    required: true

runs:
  using: composite
  steps:
    - name: Download LURBANSKI_TEST1_KEY
      if: ${{ inputs.var == 'lurbanski1' }}
      uses: hashicorp/vault-action@v2.4.1
      with:
        url: REMOVED
        namespace: REMOVED
        method: kubernetes
        role: REMOVED
        path: REMOVED
        secrets: |
          REMOVED LURBANSKI_TEST1_KEY | LURBANSKI_TEST

    - name: Download LURBANSKI_TEST2_KEY
      if: ${{ inputs.var == 'lurbanski2' }}
      uses: hashicorp/vault-action@v2.4.1
      with:
        url: REMOVED
        namespace: REMOVED
        method: kubernetes
        role: REMOVED
        path: REMOVED
        secrets: |
          REMOVED LURBANSKI_TEST2_KEY | LURBANSKI_TEST

    - name: Show LURBANSKI_TEST
      run: |
        var=${{ env.LURBANSKI_TEST }}
        echo ${var:0:1}UUU${var:1}
      shell: bash

**Expected behavior**
The X action should see the Y variable with a new value when it is called second time.

**Log Output**
<img width="862" alt="image" src="https://user-images.githubusercontent.com/89976258/180954201-66fb3bc2-0d7e-4aa3-af0e-0cfbc1bcec60.png">
