### ISSUE TITLE
[BUG] set-output workflow command deprecated

### ISSUE THREAD

**Issue by jasonhancock** [hashicorp/vault-action#384]
**Describe the bug**
If using outputs, you get a warning message as the `set-output` workflow command has been deprecated in favor of using an environment file:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**To Reproduce**
```
    - name: vault secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.2
      with:
        exportEnv: false
        url: https://vault.example.com
        method: approle
        namespace: your-vault-namespace
        roleId: your-vault-approle-id
        secretId: your-vault-approle-secret
        secrets: |
          path/to/a/secret data | your_output_name ;
```

**Expected behavior**
Output set via the $GITHUB_OUTPUT environment file instead of the "set-output" workflow command.
