### ISSUE TITLE
[BUG] update 

### ISSUE THREAD

**Issue by jasonhancock** [hashicorp/vault-action#385]
**Describe the bug** 

When running the action, a warning message is shown:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: hashicorp/vault-action
```

**To Reproduce**

```
    - name: vault secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.2
      with:
        exportEnv: false
        url: https://vault.example.com
        method: approle
        namespace: your-vault-namespace
        roleId: your-vault-approle-id
        secretId: your-vault-approle-secret
        secrets: |
          path/to/a/secret data | your_output_name ;
```

**Expected behavior**

No warning messages
