### ISSUE TITLE
[BUG] Get Vault Secrets responds with 404

### ISSUE THREAD

**Issue by tkowalewski** [hashicorp/vault-action#389]
**Describe the bug**
`Get Vault Secrets` responds with 404

<img width="1488" alt="Zrzut ekranu 2022-10-26 o 13 29 48" src="https://user-images.githubusercontent.com/1430916/198015162-b9d3ed1b-8d76-402f-ac44-cedb7aaeedac.png">

**To Reproduce**
```
name: Rails - Install dependencies, run rspec and linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  main:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      vault:
        image: vault:1.12.0
        ports: ['8200:8200']
        env:
          VAULT_ADDR: "http://0.0.0.0:8200"
          VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://localhost:8200
          token: "vault-plaintext-root-token"
          secrets: |
            secret/data/0.1.0 RAILS_SERVE_STATIC_FILES | true;
            secret/data/0.1.0 FAKE_INFLUENCE_VARIABLE | test;
            secret/data/0.1.0 RAILS_ENV | test;
            secret/data/0.1.0 DATABASE_URL | postgresql://postgres:@localhost/fake_influence_test;
            secret/data/0.1.0 REDIS_URL | localhost:6379;
            secret/data/0.1.0 SECRET_KEY_BASE | secretkeybase;
            secret/data/0.1.0 RAILS_MASTER_KEY | 4e9599e019a1f68436a1df391569daa9
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Run rspec
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: "vault-plaintext-root-token"
        run: |
          bin/rails db:create db:schema:load
          bin/rake assets:precompile
          bin/rspec
      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2
      - name: Run linters
        run: |
          bin/rubocop --parallel
```

**Expected behavior**
Vault should only store secrets? 

**Log Output**
```
Run hashicorp/vault-action@v2.4.0
  with:
    url: http://localhost:8200
    token: vault-plaintext-root-token
    secrets: secret/data/0.1.0 RAILS_SERVE_STATIC_FILES | true;
  secret/data/0.1.0 FAKE_INFLUENCE_VARIABLE | test;
  secret/data/0.1.0 RAILS_ENV | test;
  secret/data/0.1.0 DATABASE_URL | ***localhost/fake_influence_test;
  secret/data/0.1.0 REDIS_URL | localhost:6379;
  secret/data/0.1.0 SECRET_KEY_BASE | secretkeybase;
  secret/data/0.1.0 RAILS_MASTER_KEY | 4e9599e019a1f68436a1df39[15](https://github.com/paladinsoftware/fake_influence/actions/runs/3328185136/jobs/5504751275#step:3:15)69daa9
  
    method: token
    kubernetesTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token
    exportEnv: true
    exportToken: false
    tlsSkipVerify: false
    jwtTtl: 3600
::group::Get Vault Secrets
Get Vault Secrets
  ::endgroup::
Error: Response code 404 (Not Found)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Import Secrets
```
