### ISSUE TITLE
[FEAT] Automatically revoke token after completion of action

### ISSUE THREAD

**Issue by backjo** [hashicorp/vault-action#427]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to have my vault credentials automatically revoked after completion of my action. 

**Describe the solution you'd like**
I'd like the vault action to automatically revoke tokens after the action is complete, unless I tell it not to. Ideally, this could be accomplished via `runs.post` https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs

**Describe alternatives you've considered**
We currently do this ourselves on every action, but less boilerplate would be nice.
```yaml
-      name: Revoke tokens
        if: always()
        run: |
          curl -XPOST -sv -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" https://vault.company.com/v1/auth/token/revoke-self 
```
