### ISSUE TITLE
[BUG] oncancel handler error on macos-latest

### ISSUE THREAD

**Issue by jbrodriguez** [hashicorp/vault-action#445]
**Describe the bug**
i'm getting an error running the action on a macos-latest image, i tried with the v2 action and even the main version,  having the same issue

**To Reproduce**
```yaml
    - name: Import Workflow Secrets
      uses: hashicorp/vault-action@main
      with:
        url: ${{ inputs.vaultUrl }}
        method: approle
        roleId: ${{ inputs.roleId }}
        secretId: ${{ inputs.secretId }}
        secrets: ${{ inputs.secrets }}
        exportToken: true
```

**Expected behavior**
it should just work :)

**Log Output**
For the most verbose logs, [add a secret called `ACTIONS_STEP_DEBUG` with the value `true`](https://github.com/actions/toolkit/blob/main/docs/action-debugging.md). Then, re-run the workflow if possible and post the *raw logs* for the step here with any sensitive information masked or removed.
```
/Users/runner/work/_actions/hashicorp/vault-action/main/dist/index.js:17305
					throw new Error('The `onCancel` handler was attached after the promise settled.');
					      ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/Users/runner/work/_actions/hashicorp/vault-action/main/dist/index.js:17305:12)
    at makeRequest (/Users/runner/work/_actions/hashicorp/vault-action/main/dist/index.js:3622:13)
    at Request.<anonymous> (/Users/runner/work/_actions/hashicorp/vault-action/main/dist/index.js:3727:17)
    at Object.onceWrapper (node:events:642:26)
    at Request.emit (node:events:527:28)
    at Timeout.retry (/Users/runner/work/_actions/hashicorp/vault-action/main/dist/index.js:5251:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Additional context**
it seems to work only once, then addtional attempts just fail :(
