### ISSUE TITLE
[BUG] Warning about outputToken being an unexpected input

### ISSUE THREAD

**Issue by andreaso** [hashicorp/vault-action#460]
**Describe the bug**

Just tried out the new `vault_token` output added by #441. While I'm happy to report that the new output works fine there is the minor issue of the `outputToken` input generating a Warning about being an unexpected input.

```
Warning: Unexpected input(s) 'outputToken', valid inputs are ['url', 'secrets', 'namespace', 'method', 'role', 'path', 'token', 'roleId', 'secretId', 'githubToken', 'kubernetesTokenPath', 'username', 'password', 'authPayload', 'extraHeaders', 'exportEnv', 'exportToken', 'caCertificate', 'clientCertificate', 'clientKey', 'tlsSkipVerify', 'jwtPrivateKey', 'jwtKeyPassword', 'jwtGithubAudience', 'jwtTtl', 'secretEncodingType']
```

**To Reproduce**

```YAML
  - name: Authenticate towards Vault
    id: vault_auth
    uses: hashicorp/vault-action@v2.6.0
    with:
      method: jwt
      jwtGithubAudience: a-test-audience
      jwtTtl: 300
      url: https://vault.example.com:8200/
      path: github-oidc
      role: cert-action-at-user
      outputToken: true
```

**Expected behavior**

To not receive a warning about `outputToken` being an unexpected input.

**Additional context**

I suspect that this simply is a matter of the new `outputToken` input not having been defined in [action.yml](https://github.com/hashicorp/vault-action/blob/main/action.yml).
