### ISSUE TITLE
[BUG] The Vault action fails if the secret key contains a dot when using wildcards

### ISSUE THREAD

**Issue by hazerlin-houzz** [hashicorp/vault-action#541]
## Vault server version
v1.8.2 enterprise

## vault-action version
v2

## Describe the bug
The Vault Action fails if any secret key contains a dot when using wildcards
Example: `addvertise_link.json`

## To Reproduce
Fetch all secrets in certain folder
```
- name: Get Secrets from Vault
        uses: hashicorp/vault-action@v2
        id: import-secrets
        with:
          url: "https://vault...."
          method: kubernetes
          role: role
          path: path
          kubernetesTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token
          tlsSkipVerify: false
          secrets: |
            folder/data/key1/key2/key3/key4 * | CONFIG_;
```
But if there is a secret include dot when using wildcards, such as `addvertise_link.json`. The workflow will fail.

Error message
`Error: Unable to retrieve result for data.data."`*`". No match data was found. Double check your Key or Selector.`

## Expected behavior
Get all secrets in specific folder
