### ISSUE TITLE
[FEAT] Add Option: `ignoreKeyNotFound`

### ISSUE THREAD

**Issue by xsfa** [hashicorp/vault-action#551]
## Is your feature request related to a problem? Please describe.
When programmatically passing in vault keys, if the key does not exist I would like the option for the resulting value to be a null or default value.

## Describe the solution you'd like

```yml
- name: Import Secrets
  uses: actions/vault-action@v3.0.0
  with:
    url: ${{ env.url }}
    method: approle
    roleId: ${{ env.role_id }}
    secretId: ${{ env.secret_id }}
    caCertificate: ${{ secrets.vault_ca_cert }}
    ignoreKeyNotFound: true # ***
    defaultValue: null # *** or 'string', defaults to null
    secrets: |
      ${{ env.secret_path }} credentials.${{ env.PREFIX }}.username | username ;
      ${{ env.secret_path }} credentials.${{ env.PREFIX }}.password | password ;
 ```

## Describe alternatives you've considered
- Setting a default value to all possible keys
- Conditionally calling `vault-action`
